server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost

logging:
  level:
    edu.sust: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

